CREATE TABLE usercredential(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR(100),
    username VARCHAR(50),
    password VARCHAR(50)
);
 
INSERT INTO usercredential(fullname, username, password)
VALUES('User Aforo255', 'aforo255','123456');
INSERT INTO usercredential(fullname, username, password)
VALUES('Paolo Guerrero', 'pguerrero','654977');
INSERT INTO usercredential(fullname, username, password)
VALUES('Renato Tapia', 'rtapia','963258');
INSERT INTO usercredential(fullname, username, password)
VALUES('Alex Valera', 'avalera','741256');