CREATE TABLE account(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DECIMAL,
    customerid INTEGER,
    fullname VARCHAR(100)
);
 
INSERT INTO account(amount, customerid, fullname)
VALUES(1000, 1,'Juan Soto Pacherre');
INSERT INTO account(amount, customerid, fullname)
VALUES(5000, 2,'Marcos Chuyes Alva');
INSERT INTO account(amount, customerid, fullname)
VALUES(2000, 2,'Marcos Chuyes Alva');
INSERT INTO account(amount, customerid, fullname)
VALUES(4000, 3,'Alberto Ramos Zambrano');
INSERT INTO account(amount, customerid, fullname)
VALUES(3000, 1,'Juan Soto Pacherre');
INSERT INTO account(amount, customerid, fullname)
VALUES(1500, 3,'Alberto Ramos Zambrano');
INSERT INTO account(amount, customerid, fullname)
VALUES(6000, 4,'Luis Suarez Garcia');